import {
  Type,
  AlignLeft,
  Mail,
  Phone,
  Calendar,
  List,
  CircleDot,
  CheckSquare,
  Hash,
  Heading
} from "lucide-react";

export const FIELD_TYPES = [
  {
    type: "section",
    label: "Section",
    icon: Heading,
    defaultLabel: "Section Title",
    placeholder: "",
    defaultDescription: "",
  },
  {
    type: "text",
    label: "Text",
    icon: Type,
    defaultLabel: "Short answer",
    placeholder: "Enter text",
  },
  {
    type: "textarea",
    label: "Textarea",
    icon: AlignLeft,
    defaultLabel: "Long answer",
    placeholder: "Enter long answer",
  },
  {
    type: "email",
    label: "Email",
    icon: Mail,
    defaultLabel: "Email Address",
    placeholder: "example@email.com",
  },
  {
    type: "phone",
    label: "Phone",
    icon: Phone,
    defaultLabel: "Mobile Number",
    placeholder: "01XXXXXXXXX",
  },
  {
    type: "number",
    label: "Number",
    icon: Hash,
    defaultLabel: "Number",
    placeholder: "Enter number",
  },
  {
    type: "date",
    label: "Date",
    icon: Calendar,
    defaultLabel: "Date",
    placeholder: "",
  },
  {
    type: "dropdown",
    label: "Dropdown",
    icon: List,
    defaultLabel: "Select option",
    placeholder: "",
    defaultOptions: ["Option 1", "Option 2"],
  },
  {
    type: "radio",
    label: "Radio",
    icon: CircleDot,
    defaultLabel: "Choose one",
    placeholder: "",
    defaultOptions: ["Option 1", "Option 2"],
  },
  {
    type: "checkbox",
    label: "Checkbox",
    icon: CheckSquare,
    defaultLabel: "Choose multiple",
    placeholder: "",
    defaultOptions: ["Option 1", "Option 2"],
  },
];