export const REPORT_SOURCES = {

    participant_master: {
    label: "Participant Master Report",
    collection: "participants",
    type: "dataset",
    defaultColumns: [
        "participant_code",
        "name",
        "phone",
        "email",
        "gender",
        "date_of_birth",
        "age",
        "cohort_name",
        "registration_status",
        "selection_status",
        "enrollment_status",
        "graduation_status",
        "submitted_at",
    ],
    columns: [],
    },

  participants: {
    label: "Participants",
    collection: "participants",
    type: "fixed",
    defaultColumns: [
      "participant_code",
      "name",
      "phone",
      "email",
      "cohort_name",
      "registration_status",
      "selection_status",
      "enrollment_status",
      "graduation_status",
      "submitted_at",
    ],
    columns: [
      { key: "participant_code", label: "Participant Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email" },
      { key: "cohort_name", label: "Cohort" },
      { key: "cohort_code", label: "Cohort Code" },
      { key: "registration_status", label: "Registration Status" },
      { key: "selection_status", label: "Selection Status" },
      { key: "enrollment_status", label: "Enrollment Status" },
      { key: "graduation_status", label: "Graduation Status" },
      { key: "project_status", label: "Project Status" },
      { key: "submitted_at", label: "Submitted At" },
      { key: "created_at", label: "Created At" },
      { key: "updated_at", label: "Updated At" },
    ],
  },

  form_responses: {
    label: "Form Responses",
    collection: "form_responses",
    type: "dynamic",
    defaultColumns: [
      "participant_code",
      "search_name",
      "search_phone",
      "search_email",
      "cohort_name",
      "form_title",
      "submitted_at",
    ],
    columns: [
      { key: "participant_code", label: "Participant Code" },
      { key: "search_name", label: "Name" },
      { key: "search_phone", label: "Phone" },
      { key: "search_email", label: "Email" },
      { key: "cohort_name", label: "Cohort" },
      { key: "cohort_code", label: "Cohort Code" },
      { key: "form_title", label: "Form" },
      { key: "submitted_at", label: "Submitted At" },
    ],
  },
  participant_complete: {
        label: "Participant Complete Report",
        collection: "participants",
        type: "joined",
        defaultColumns: [
            "participant_code",
            "name",
            "phone",
            "email",
            "cohort_name",
            "registration_status",
            "submitted_at",
        ],
        columns: [
            { key: "participant_code", label: "Participant Code" },
            { key: "name", label: "Name" },
            { key: "phone", label: "Phone" },
            { key: "email", label: "Email" },
            { key: "cohort_name", label: "Cohort" },
            { key: "cohort_code", label: "Cohort Code" },
            { key: "registration_status", label: "Registration Status" },
            { key: "selection_status", label: "Selection Status" },
            { key: "enrollment_status", label: "Enrollment Status" },
            { key: "graduation_status", label: "Graduation Status" },
            { key: "project_status", label: "Project Status" },
            { key: "submitted_at", label: "Submitted At" },
        ],
    }
};