export const ROUTES = {
  login: "/",
  admin: "/admin",

  cohorts: "/admin/cohorts",
  createCohort: "/admin/cohorts/create",
  editCohort: "/admin/cohorts/:id/edit",

  forms: "/admin/forms",
  createForm: "/admin/forms/create",
  editForm: "/admin/forms/:id/edit",
  formBuilder: "/admin/forms/:id/builder",

  championRegistration: "/champions/register",
  championActivate: "/champions/activate",
  championHome: "/champions",
  championMyProfile: "/champions/profile",
  championFGDs: "/champions/fgds",
  championFGDDetail: "/champions/fgds/:fgdId",
  championParticipantProfile: "/champions/fgds/:fgdId/participants/:participantId",
  championFGDRosters: "/champions/fgd-rosters",
  championFGDRosterDetail: "/champions/fgd-rosters/:cohortId",
  championClassroom: "/champions/classroom",
  championProjects: "/champions/projects",
  championProjectDetail: "/champions/projects/:projectId",

  participantHome: "/participant",
  participantAchievements: "/participant/achievements",
  champions: "/admin/champions",
  championProfile: "/admin/champions/:championId",
  selectionCommittee: "/admin/champions/selection-committee",
  selectionFGDs: "/admin/participants/selection/fgds",
  selectionCohortFGDs: "/admin/participants/selection/fgds/:cohortId",
  selectionFGDDetails: "/admin/participants/selection/fgds/details/:fgdId",
  selectionRosters: "/admin/participants/selection/rosters",
  selectionRosterDetail: "/admin/participants/selection/rosters/:cohortId",

  participants: "/admin/participants",
  bulkImportParticipants: "/admin/participants/bulk-import",
  projects: "/admin/projects",
  reports: "/admin/reports",
  settings: "/admin/settings",
};